### PR TITLE
adding persian version

### PR DESCRIPTION
**Pull request by bistcuite**

### CODE REVIEW

**Review by mmdbalkhi — CHANGES_REQUESTED** [review]
Please add the Persian Page link to the main page, thank you.

**Review by mmdbalkhi — CHANGES_REQUESTED** [review]
@bistcuite colours are not identical. In En like **Orangeish** and Persian Ver. is **Blueish**.  Imo problem is in The `bootstrap.rtl`. If possible please fix it. 

abc

**Comment by bistcuite** [comment]
> Please add the Persian Page link to the main page, thank you.

Added

**Review by mmdbalkhi — APPROVED** [review]

**Comment by mmdbalkhi** [comment]
@bistcuite thank you

**Pull request merged**
